spring:
  kafka:
    properties:
      schema.registry.url: http://kafka-schema-registry:8081
    consumer:
      bootstrap-servers: kafka:29092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    # Specific AWS conf
      region: not-used
      avroRecordType: not-used
      timeToLiveMillis: 0 #not-used
      cacheSize: 0 #not-used
    # END OF Specific AWS Conf
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    # Specific AWS conf
      region: not-used
      dataFormat: not-used
      schemaAutoRegistrationEnabled: true #not-used
      schemaName: not-used
      registry:
        name:  not-used
      timeToLiveMillis: 0 #not-used
      cacheSize: 0 #not-used
      compatibility: not-used
      description: not-used 
      compression: not-used
    # END OF Specific AWS Conf
